Sprint 2/step1
NatashaSolntseva/react-burger pull request #3
Opened 2022-01-15 15:51 UTC by NatashaSolntseva

2022-01-15 21:58 UTC, grishbar requested changes
Текущее задание выполнено верно, контекстом везде воспользовалась правильно, круто, что пытаешься документировать код, но слишком переусердствуешь с этим.
Также обрати внимание, что после того как твой пулл реквест прошел ревью, тебе надо замерджить твою ветку в main, (во первых так просходит разработка, что ты отправляешь пр (реквест на влитие твоего кода в главную ветку) и ждешь когда твои коллеги его посмотрят, и когда все ок, то вливашеь свой код в главную ветку, а во вторых пока ты не влила свои предыдущие ветки, при каждом новом пулл реквесте в changed files попадают все изменения, а не только новые) Сейчас старые пуллреквесты вливать не надо, вольешь, потом этот, когда все будет ок, и каждый следующий после него.

Замечания, которые надо исправить для принятия работы:

- [x] Не нужно объединять переменные состояния в одну сущность без необходимости
- [x] Добавить обработку статуса ответа при запросе
- [ ] Избавиться от хранения невалидные данных в переменных состояния
- [x] Удалить ненужные комментарии
- [x] Избавиться от длинных комментариев в пользу коротких
- [x] Переименовать не совсем удачно названные переменные
- [x] Задать корректные alt атрибуты картинкам
- [x] Избавиться от всех ошибок в консоли, в частности от (no-unused-vars)

Предстоит большая работа, удачи в рефакторинге.

2022-01-15 21:58 UTC, grishbar commented on README.md
> +<h1 align="center"><a  href="https://natashasolntseva.github.io/react-burger/" target="_blank"><img src="./readme_src/header.png" width="100%" alt="Readme_header"></a></h1>
`можно лучше`
в readme.md используется [markdown разметка](https://www.markdownguide.org/basic-syntax/), будет лучше, если ты переделаешь на нее, чем будешь вставлять html код

2022-01-15 21:58 UTC, grishbar commented on public/index.html
> +    <link rel="icon" href="%PUBLIC_URL%/favicon1.ico" />
`отлично`
круто, что решила добавить meta теги в свой проект

2022-01-15 21:58 UTC, grishbar commented on src/components/app/app.jsx
> +  });
`надо исправить`
такие состояния компонента нужно разделять, во первых это разные абстракции поэтому семантически так будет более корректно, во вторых если у тебя будет меняться хоть одно из этих полей, то будет перерендываться все поля с ними связанными а не только измененные, что не очень, теряешь в производительности, также манипулировать с разделенными примитивными объектами намного проще, чем с большим сложным объектом
https://reactjs.org/docs/hooks-faq.html#should-i-use-one-or-many-state-variables

2022-01-15 21:58 UTC, grishbar commented on src/components/app/app.jsx
> +        }));
`надо исправить`
если получение ингредиентов не удалось, то не нужно хранить потенциально невалидные данные в стейте,           `...state,` этого быть не должно, возвращай initialState (тот который ты изначально задаешь) и `hasError: true, error: error,`

2022-01-15 21:58 UTC, grishbar commented on src/components/app/app.jsx
> +  //_______________________________функционал модельных окон___________________________________
`надо исправить`
такой длинный комментарий с подчеркиваниями читается намного тяжелее простого `// функционал модельных окон` или можно:
```
/*
* функционал модельных окон
* /
```

2022-01-15 21:58 UTC, grishbar commented on src/components/app/app.jsx
> +      //console.log("modalIngredientDat image", modalIngredientData.image);
`надо исправить`
комментарии, которые не документируют код должны быть удалены

2022-01-15 21:58 UTC, grishbar commented on src/components/app/app.jsx
> +  });
`надо исправить`
не зачем тут хранить объект со свойством дата, можно сразу хранить ингредиенты

2022-01-15 21:58 UTC, grishbar commented on src/components/app/app.jsx
> +    let modalIngredientData = null;
`надо исправить`
эта переменная тут не нужна, можно сделать без нее

2022-01-15 21:58 UTC, grishbar commented on src/components/app/app.jsx
> +    //console.log("bun make order", bun);
`надо исправить`
пройдись пожалуйста по всему проекту, и удали везде ненужные комментарии

2022-01-15 21:58 UTC, grishbar commented on src/components/app/app.jsx
> +    //console.log("order total", orderIngredientList);
`надо исправить`
зачем вводишь абстракции, которые используешь всего один раз? Они тут излишни. Вместо всех этих строчек сделай получение id заказа в одну строчку, это не сложно и прочитать одну строчку в разы проще чем 14

2022-01-15 21:58 UTC, grishbar commented on src/components/app/app.jsx
> +      setOrderInfo({ ...orderInfo, isCreatingOrder: true });
`надо исправить`
тут получается, что при каждом заказе ты вначале вставляешь старый orderId в данные о заказе, это неправильно, тут тоже надо вставлять initialState и `isCreatingOrder: true`

2022-01-15 21:58 UTC, grishbar commented on src/components/app/app.jsx
> +      setOrderInfo({ ...orderInfo, isCreatingOrder: false, error: error });
`надо исправить`
тут тоже initialState вместо orderInfo

2022-01-15 21:58 UTC, grishbar commented on src/components/app/appStyles.module.css
> +/*весь контент*/
`можно лучше`
на мой взгляд документация css кода не приносит пользы

2022-01-15 21:58 UTC, grishbar commented on src/components/burger-constructor/burgerConstructor.jsx
> +//контекст
`надо исправить`
это хорошо, что ты стараешь все документировать, но очевидные строчки кода не стоит документировать очевидными комментариями. Комментарии нужны, чтобы задокументировать какой то блок кода, чтобы не читать, что в нем написано, или чтобы объяснить какую то неочевидную, непонятную, неожидаемую строчку, тут у тебя не этот случай.

2022-01-15 21:58 UTC, grishbar commented on src/components/burger-constructor/burgerConstructor.jsx
> +  //}
`надо исправить`
тоже не забудь удалить

2022-01-15 21:58 UTC, grishbar commented on src/components/burger-constructor/burgerConstructor.jsx
> +            isLocked={true}
`можно лучше`
можно просто isLocked

2022-01-15 21:58 UTC, grishbar commented on src/components/burger-constructor/burgerConstructor.jsx
> +//Это нужно исправить везде, где отрисовываете массив через map
`надо исправить`
эти комментарии к чему тут? кажется они потерялись

2022-01-15 21:58 UTC, grishbar commented on src/components/burger-ingredients/burgerIngredients.jsx
> +  );
`надо исправить`
все переменные которые содержат массив должны явно об этом говорить, у тебя должно быть что то типа: `buns, sauces, mains`

2022-01-15 21:58 UTC, grishbar commented on src/components/burger-ingredients/burgerIngredients.jsx
> +          }}
`надо исправить`
[нельзя создавать функции внутри jsx](https://qastack.ru/programming/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind), это плохо влияет на производительность, и не [рекомендуется разработчиками реакта](https://ru.reactjs.org/docs/faq-functions.html)
Также обрати внимание, что тут в трех местах так сделала, надо везде поправить

2022-01-15 21:58 UTC, grishbar commented on src/components/burger-ingredients/burgerIngredients.jsx
> +      >
`надо исправить`
тут тоже избавиться от создания функций внутри jsx, удалить ненужные комментарии, и в твоем коде не должно быть таких "магических переменных" как - 440 , надо вынести это число в переменную и дать осмысленное название, кто то будет читать твой код, и для этого человека абсолютно непонятно, что такое 440

2022-01-15 21:58 UTC, grishbar commented on src/components/burger-ingredients/ingredient-element/ingredientElement.jsx
> +  }
`надо исправить`
не надо давать переменным/функциям такие абстрактные названия, совсем непонятно, что твоя функция выполняет. Также в компоненте не принято создавать функции через Function Declaration, нужно их создавать при помощи Function Expression, [здесь](https://medium.com/@mandeep1012/function-declarations-vs-function-expressions-b43646042052) можно прочитать про виды создания функций. И не забудь, что функции обрабатывающие какие либо события должны начинаться со слова handle

2022-01-15 21:58 UTC, grishbar commented on src/components/burger-ingredients/ingredient-element/ingredientElement.jsx
> +        <img alt = "Фото элемента" src={image} className = {styles.element_img} />
`надо исправить`
представь, что ты слепой человек и у тебя есть картинка ингридента скрин ридер прочитает эту картинку как "Фото элемента", кажется, что это не так должно работать

2022-01-15 21:58 UTC, grishbar commented on src/components/burger-ingredients/ingredient-group/ingredientGroup.jsx
> +              key = {burgerItem._id}
`можно лучше`
сейчас не ошибка, но в будущем у тебя тут могут повторяться ингредиенты и соответственно тут у тебя будут случаться коллизии , подумай над тем, как задать тут всегда уникальный key

2022-01-15 21:58 UTC, grishbar commented on src/components/burger-ingredients/ingredient-group/ingredientGroup.jsx
> +*/
`надо исправить`
тут тоже какие то вырванные из контекста комментарии

2022-01-15 21:58 UTC, grishbar commented on src/components/modal/modal.jsx
> +import { isPropertySignature } from "typescript";
`надо исправить`
<img width="1108" alt="Screen Shot 2022-01-16 at 00 49 19" src="https://user-images.githubusercontent.com/32193933/149638786-a7b7a23a-39af-45f9-9a3c-e8255a947c82.png">
обрати внимание на то, что тебе выводит консоль в идеале там не должно быть никаких ворнингов и ошибок, ты можешь от всех ошибок в консоли избавиться, займись этим пожалуйста

2022-01-16 13:00 UTC, NatashaSolntseva commented on README.md
> +<h1 align="center"><a  href="https://natashasolntseva.github.io/react-burger/" target="_blank"><img src="./readme_src/header.png" width="100%" alt="Readme_header"></a></h1>
Переделала

2022-01-16 13:12 UTC, NatashaSolntseva commented on src/components/app/app.jsx
> +  });
исправлено

2022-01-16 13:20 UTC, NatashaSolntseva commented on src/components/app/app.jsx
> +        }));
исправлено

2022-01-16 13:21 UTC, NatashaSolntseva commented on src/components/app/app.jsx
> +  //_______________________________функционал модельных окон___________________________________
сократила

2022-01-16 13:22 UTC, NatashaSolntseva commented on src/components/app/app.jsx
> +      //console.log("modalIngredientDat image", modalIngredientData.image);
удалила

2022-01-16 13:26 UTC, NatashaSolntseva commented on src/components/app/app.jsx
> +    //console.log("order total", orderIngredientList);
совместила, если верно поняла замечание

2022-01-16 13:26 UTC, NatashaSolntseva commented on src/components/app/app.jsx
> +    //console.log("bun make order", bun);
тут удалила

2022-01-16 13:31 UTC, NatashaSolntseva commented on src/components/app/appStyles.module.css
> +/*весь контент*/
убрала

2022-01-16 13:46 UTC, NatashaSolntseva commented on src/components/burger-constructor/burgerConstructor.jsx
> +//контекст
ок
я скорее сейчас для себя пишу, ибо через неделю уже как и не ты писал код. а контекст придется переписывать на redux

2022-01-16 13:47 UTC, NatashaSolntseva commented on src/components/burger-constructor/burgerConstructor.jsx
> +  //}
сделано

2022-01-16 13:50 UTC, NatashaSolntseva commented on src/components/burger-constructor/burgerConstructor.jsx
> +            isLocked={true}
ок

2022-01-16 13:50 UTC, NatashaSolntseva commented on src/components/burger-constructor/burgerConstructor.jsx
> +//Это нужно исправить везде, где отрисовываете массив через map
это от прошлого ревью..

2022-01-16 13:54 UTC, NatashaSolntseva commented on src/components/burger-ingredients/burgerIngredients.jsx
> +  );
ок

2022-01-16 14:35 UTC, NatashaSolntseva commented on src/components/burger-ingredients/burgerIngredients.jsx
> +          }}
сделано

2022-01-16 14:36 UTC, NatashaSolntseva commented on src/components/burger-ingredients/burgerIngredients.jsx
> +      >
удалила, в задании спринта не было этого функционала

2022-01-16 14:38 UTC, NatashaSolntseva commented on src/components/burger-ingredients/ingredient-element/ingredientElement.jsx
> +        <img alt = "Фото элемента" src={image} className = {styles.element_img} />
поменяла

2022-01-16 14:44 UTC, NatashaSolntseva commented on src/components/burger-ingredients/ingredient-element/ingredientElement.jsx
> +  }
сделано

2022-01-16 14:45 UTC, NatashaSolntseva commented on src/components/burger-ingredients/ingredient-group/ingredientGroup.jsx
> +*/
удалила

2022-01-16 15:32 UTC, NatashaSolntseva commented on src/components/modal/modal.jsx
> +import { isPropertySignature } from "typescript";
сделала

2022-01-16 15:43 UTC, NatashaSolntseva commented on src/components/app/app.jsx
> +  });
сделано

2022-01-16 15:44 UTC, NatashaSolntseva commented on src/components/app/app.jsx
> +    let modalIngredientData = null;
сделала, но не совсем без нее

2022-01-16 16:12 UTC, NatashaSolntseva commented on src/components/app/app.jsx
> +      setOrderInfo({ ...orderInfo, isCreatingOrder: true });
исправила вроде бы

2022-01-16 16:12 UTC, NatashaSolntseva commented on src/components/app/app.jsx
> +      setOrderInfo({ ...orderInfo, isCreatingOrder: false, error: error });
исправила вроде бы

2022-01-16 22:18 UTC, grishbar approved these changes
Великолепно! все ошибки исправлены, работу принимаю, удачи в дальнейшем обучении

2022-01-16 22:24 UTC, grishbar commented
не забудь влить этот пр в main

2022-01-17 07:15 UTC, merged